import Foundation
import Observation
import AuthenticationServices

@Observable
@MainActor
class AppState {
    var athleteContext: AthleteContext = .preview
    var fitnessSnapshots: [FitnessSnapshot] = FitnessSnapshot.previewSnapshots
    var segments: [SegmentScore] = SegmentScore.previewSegments
    var arcMessages: [ArcMessage] = []

    // Streaming state for the in-progress Enzo response
    var isStreaming = false
    var streamingText = ""

    // Auth state — populated after successful OAuth flow
    var isAuthenticated: Bool = false
    var stravaAthleteId: Int64? = nil
    var supabaseUserId: UUID? = nil

    // Onboarding state — persisted to UserDefaults
    var hasCompletedOnboarding: Bool = UserDefaults.standard.bool(forKey: "hasCompletedOnboarding") {
        didSet { UserDefaults.standard.set(hasCompletedOnboarding, forKey: "hasCompletedOnboarding") }
    }

    // Sync state
    var isSyncing: Bool = false
    var isSyncingPhase2: Bool = false

    // Arc content — generated by Claude, updated on each launch
    var briefingText: String = AthleteContext.previewBriefing
    var lookaheadText: String = AthleteContext.previewLookahead
    var isGeneratingBriefing: Bool = false
    var isGeneratingLookahead: Bool = false

    private let claudeService: ClaudeService
    private let stravaService: StravaService
    private let supabaseService: SupabaseService
    private let syncService: SyncService

    init() {
        let strava   = StravaService()
        let supabase = SupabaseService()
        claudeService  = ClaudeService()
        stravaService  = strava
        supabaseService = supabase
        syncService    = SyncService(stravaService: strava, supabaseService: supabase)

        // Restore auth state from Keychain on launch
        if let idString = KeychainHelper.load(for: KeychainHelper.stravaAthleteId),
           let id = Int64(idString) {
            isAuthenticated = true
            stravaAthleteId = id
        }
        if let uuidString = KeychainHelper.load(for: KeychainHelper.supabaseUserId),
           let uuid = UUID(uuidString: uuidString) {
            supabaseUserId = uuid
        }
    }

    // MARK: - Context loading

    /// Fetches fitness snapshots, user profile, and active goal from Supabase,
    /// then builds a live AthleteContext. No-ops gracefully if not authenticated.
    func loadContext() async {
        guard let userId = supabaseUserId else { return }

        do {
            async let snapshotRows = supabaseService.fetchFitnessSnapshots(userId: userId)
            async let profile = supabaseService.fetchUserProfile(userId: userId)
            async let goalRow = supabaseService.fetchActiveGoal(userId: userId)

            let (rows, userProfile, activeGoal) = try await (snapshotRows, profile, goalRow)

            let snapshots = rows.map { $0.toSnapshot() }
                .sorted { $0.month < $1.month }

            let context = AthleteContext.build(
                name: userProfile.displayName,
                snapshots: snapshots,
                goalRow: activeGoal,
                lastActivityDate: userProfile.lastActivityDate
            )

            fitnessSnapshots = snapshots
            athleteContext = context

            NSLog("[Context] Loaded: \(snapshots.count) snapshots, fitness=\(context.currentFitnessLabel), trend=\(context.trendDirection)")

            // Auto-complete onboarding for existing users who already have a goal.
            if activeGoal != nil && !hasCompletedOnboarding {
                hasCompletedOnboarding = true
                NSLog("[Onboarding] Existing user — marking onboarding complete")
            }

            // Load real segment scores from Supabase (no-op if table is empty).
            await loadSegments(goalSegmentName: activeGoal?.targetSegmentName)
        } catch {
            NSLog("[Context] loadContext error: \(error)")
        }
    }

    /// Fetches segment scores from Supabase and populates appState.segments.
    /// Marks the goal segment if a goal is active.
    func loadSegments(goalSegmentName: String? = nil) async {
        guard let userId = supabaseUserId else { return }
        do {
            let rows = try await supabaseService.fetchSegmentScores(userId: userId)
            guard !rows.isEmpty else {
                NSLog("[Segments] No segment rows in Supabase yet — keeping preview data")
                return
            }
            let loaded = rows.map { row -> SegmentScore in
                var score = row.toSegmentScore()
                score.isGoalSegment = score.name == goalSegmentName
                return score
            }
            segments = loaded.sorted { $0.strikeScore > $1.strikeScore }
            NSLog("[Segments] Loaded \(loaded.count) segments from Supabase")
        } catch {
            NSLog("[Segments] loadSegments error: \(error)")
        }
    }

    /// Generates today's Arc briefing by calling Claude with the current context.
    /// Streams tokens into briefingText so the card updates progressively.
    func generateBriefing() async {
        guard supabaseUserId != nil else { return }
        isGeneratingBriefing = true
        briefingText = ""

        let prompt = AppState.briefingPrompt(context: athleteContext)
        let context = athleteContext.contextPayload(snapshots: fitnessSnapshots, segments: segments)
        let stream = await claudeService.stream(userMessage: prompt, context: context)

        for await token in stream {
            briefingText += token
        }

        isGeneratingBriefing = false
        NSLog("[Arc] Briefing generated (\(briefingText.count) chars)")
    }

    /// Generates the "what to do next" lookahead by calling Claude with the current context.
    func generateLookahead() async {
        guard supabaseUserId != nil else { return }
        isGeneratingLookahead = true
        lookaheadText = ""

        let prompt = AppState.lookaheadPrompt(context: athleteContext)
        let context = athleteContext.contextPayload(snapshots: fitnessSnapshots, segments: segments)
        let stream = await claudeService.stream(userMessage: prompt, context: context)

        for await token in stream {
            lookaheadText += token
        }

        isGeneratingLookahead = false
        NSLog("[Arc] Lookahead generated (\(lookaheadText.count) chars)")
    }

    /// Pure function — builds the briefing generation prompt. Extracted for testability.
    static func briefingPrompt(context: AthleteContext) -> String {
        "Generate today's Arc briefing. Write 2-3 sentences: where their fitness stands relative " +
        "to their goal, what the trend means, and one forward-looking line. " +
        "Be specific to their actual data — reference their current fitness label, goal segment, " +
        "and trend direction. Do not start with 'I' or 'You'."
    }

    /// Pure function — builds the lookahead generation prompt. Extracted for testability.
    static func lookaheadPrompt(context: AthleteContext) -> String {
        "Generate a 5-7 day lookahead suggestion. What should this athlete do in the next week? " +
        "Keep it loose — not a rigid plan. Be specific to their current fitness (\(context.currentFitnessLabel)), " +
        "trend (\(context.trendDirection)), and days since last ride (\(context.daysSinceLastRide)). " +
        "2-3 sentences max. Do not include any headers or labels — just the suggestion."
    }

    // MARK: - Goal setting

    func setGoal(_ segment: SegmentScore, targetDate: Date?) {
        let weeksRemaining: Int? = targetDate.map { date in
            let days = Calendar.current.dateComponents([.day], from: Date(), to: date).day ?? 0
            return max(0, days / 7)
        }

        let requiredValue = segment.fitnessValueAtPR
        let requiredLabel = SegmentScorer.requiredFitnessLabel(fitnessValueAtPR: requiredValue)
        let newGoal = GoalContext(
            segmentName: segment.name,
            requiredFitnessLabel: requiredLabel,
            requiredFitnessValue: requiredValue,
            targetDate: targetDate,
            weeksRemaining: weeksRemaining
        )

        athleteContext = AthleteContext(
            name: athleteContext.name,
            yearsActive: athleteContext.yearsActive,
            totalActivities: athleteContext.totalActivities,
            currentFitnessLabel: athleteContext.currentFitnessLabel,
            currentFitnessValue: athleteContext.currentFitnessValue,
            trendDirection: athleteContext.trendDirection,
            peakFitnessLabel: athleteContext.peakFitnessLabel,
            peakFitnessMonth: athleteContext.peakFitnessMonth,
            daysSinceLastRide: athleteContext.daysSinceLastRide,
            goal: newGoal
        )

        segments = segments.map { seg in
            var updated = seg
            updated.isGoalSegment = seg.name == segment.name
            return updated
        }

        // Persist to Supabase in the background — in-memory state is already set above.
        guard let userId = supabaseUserId else { return }
        Task {
            do {
                try await supabaseService.saveGoal(
                    userId: userId,
                    segmentName: segment.name,
                    targetDate: targetDate,
                    requiredFitnessLabel: requiredLabel,
                    requiredFitnessValue: requiredValue
                )
                NSLog("[Goal] Saved goal '\(segment.name)' to Supabase")
            } catch {
                NSLog("[Goal] Failed to save goal: \(error)")
            }
        }
    }

    func goalReactionStream(for segment: SegmentScore) async -> AsyncStream<String> {
        let prompt = AppState.goalReactionPrompt(segment: segment, athleteContext: athleteContext)
        let context = athleteContext.contextPayload(snapshots: fitnessSnapshots, segments: segments)
        return await claudeService.stream(userMessage: prompt, context: context)
    }

    /// Pure function — builds the Enzo prompt for reacting to a newly selected goal segment.
    /// Extracted for testability.
    static func goalReactionPrompt(segment: SegmentScore, athleteContext: AthleteContext) -> String {
        let fitnessAtPRLabel = AthleteContext.fitnessLabel(for: segment.fitnessValueAtPR)
        return "I want to set \(segment.name) as my PR goal. " +
               "I set that PR (\(segment.prFormatted)) on \(segment.prDate) " +
               "when I was at \(fitnessAtPRLabel) fitness. " +
               "My current fitness is \(athleteContext.currentFitnessLabel), trending \(athleteContext.trendDirection). " +
               "React to this goal choice — be honest about where I stand and whether a target date makes sense."
    }

    // MARK: - Authentication

    func disconnect() {
        KeychainHelper.delete(for: KeychainHelper.stravaAccessToken)
        KeychainHelper.delete(for: KeychainHelper.stravaRefreshToken)
        KeychainHelper.delete(for: KeychainHelper.stravaTokenExpiry)
        KeychainHelper.delete(for: KeychainHelper.stravaAthleteId)
        KeychainHelper.delete(for: KeychainHelper.supabaseUserId)
        UserDefaults.standard.removeObject(forKey: "hasCompletedOnboarding")
        UserDefaults.standard.removeObject(forKey: SyncService.lastPhase2SyncKey)
        isAuthenticated = false
        hasCompletedOnboarding = false
        stravaAthleteId = nil
        supabaseUserId = nil
        athleteContext = .preview
        fitnessSnapshots = FitnessSnapshot.previewSnapshots
        segments = SegmentScore.previewSegments
        NSLog("[Auth] Disconnected — state reset to preview")
    }

    func authenticate(contextProvider: ASWebAuthenticationPresentationContextProviding) async throws {
        let athlete = try await stravaService.authenticate(presentingFrom: contextProvider)
        let userId = try await supabaseService.createUser(
            stravaAthleteId: athlete.id,
            displayName: athlete.displayName
        )
        isAuthenticated = true
        stravaAthleteId = athlete.id
        supabaseUserId = userId
        KeychainHelper.save(userId.uuidString, for: KeychainHelper.supabaseUserId)
    }

    // MARK: - Sync

    func syncPhase1() async {
        var userId = supabaseUserId

        // Fallback: look up UUID from Supabase if not cached in Keychain (e.g. authenticated pre-Step 7)
        if userId == nil, let athleteId = stravaAthleteId {
            NSLog("[Sync] supabaseUserId missing — looking up from Supabase for athleteId \(athleteId)")
            userId = try? await supabaseService.fetchUserId(stravaAthleteId: athleteId)
            if let resolved = userId {
                supabaseUserId = resolved
                KeychainHelper.save(resolved.uuidString, for: KeychainHelper.supabaseUserId)
                NSLog("[Sync] resolved userId: \(resolved)")
            }
        }

        guard let userId else {
            NSLog("[Sync] no userId — aborting (not authenticated?)")
            return
        }

        NSLog("[Sync] starting Phase 1 for userId \(userId)")
        isSyncing = true
        do {
            try await syncService.syncPhase1(userId: userId)
            NSLog("[Sync] Phase 1 complete")
        } catch {
            NSLog("[Sync] Phase 1 error: \(error)")
        }
        isSyncing = false

        // Phase 2 runs automatically after Phase 1 completes.
        await syncPhase2()
    }

    /// Clears the Phase 2 incremental sync timestamp so the next sync re-fetches from scratch.
    func resetSyncHistory() {
        UserDefaults.standard.removeObject(forKey: SyncService.lastPhase2SyncKey)
        NSLog("[Sync] Phase 2 history reset — next sync will re-fetch from scratch")
    }

    func syncPhase2() async {
        guard let userId = supabaseUserId else {
            NSLog("[Sync] syncPhase2: no userId — aborting")
            return
        }

        NSLog("[Sync] starting Phase 2 for userId \(userId)")
        isSyncingPhase2 = true
        do {
            try await syncService.syncPhase2(userId: userId)
            NSLog("[Sync] Phase 2 complete — reloading segments")
            await loadSegments(goalSegmentName: athleteContext.goal.segmentName)
        } catch {
            NSLog("[Sync] Phase 2 error: \(error)")
        }
        isSyncingPhase2 = false
    }

    // MARK: - Messaging

    func sendMessage(_ text: String) async {
        let userMsg = ArcMessage(role: .user, content: text)
        arcMessages.append(userMsg)

        isStreaming = true
        streamingText = ""

        let context = athleteContext.contextPayload(
            snapshots: fitnessSnapshots,
            segments: segments
        )

        let tokenStream = await claudeService.stream(userMessage: text, context: context)

        for await token in tokenStream {
            streamingText += token
        }

        if !streamingText.isEmpty {
            arcMessages.append(ArcMessage(role: .enzo, content: streamingText))
        }

        streamingText = ""
        isStreaming = false
    }
}
